version: '3.8'
services:
  radius:
    image: freeradius/freeradius-server:latest
    container_name: radius
    restart: always
    network_mode: "host"
    volumes:
      - radius-data:/etc/raddb
      - radius-log:/var/log/freeradius
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  radius-data: