version: '3.8'
services:
  radius:
    image: bucchub/freeradius:latest
    container_name: radius
    restart: always
    network_mode: "host"
    volumes:
      - radius-config:/etc/raddb/client.conf
      - radius-log:/var/log/freeradius
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  radius-config:
  radius-log: