version: '3.8'
services:
  radius:
    image: bucchub/freeradius:3
    container_name: radius
    restart: always
    network_mode: "host"
    environment:
      - NPS_IP_01=${NPS_IP_01}
      - NPS_SECRETE_01=${NPS_SECRETE_01}
      - NPS_IP_02=${NPS_IP_02}
      - NPS_SECRETE_02=${NPS_SECRETE_02}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    volumes:
      - radius-config:/etc/freeradius
      - radius-log:/var/log/freeradius
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  radius-config:
  radius-log:
